self-hosted-runner:
  labels:
    - windows-11-arm # not self-hosted but actionlint fails on it

# Path-specific configurations.
paths:
  # Glob pattern relative to the repository root for matching files. The path separator is always '/'.
  # This example configures any YAML file under the '.github/workflows/' directory.
  .github/workflows/**/*.{yml,yaml}:
    # List of regular expressions to filter errors by the error messages.
    ignore:
      # Ignore errors about unknown runners/labels
      - '(?i).*is unknown\\. available labels are.*'
