coverage:
  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project: true
    patch: false
    changes: false
  notify:
    after_n_builds: 6
  comment:
    after_n_builds: 6
