coverage:
  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project: true
    patch: false
    changes: false
codecov:
  notify:
    # Wait for all 10 coverage uploads (5 OS x 2 configurations) before reporting
    after_n_builds: 10
