coverage:
  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      enabled: true
      threshold: 0.1%
    patch: false
    changes: false
codecov:
  notify:
    after_n_builds: 6
