<Project Sdk="MSTest.Sdk/4.3.3">

  <PropertyGroup>
    <RootNamespace>nietras.SeparatedValues.Test</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA2007</NoWarn>

    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sep\Sep.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  
</Project>
