name: bench

permissions: read-all

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            windows-latest,
            ubuntu-latest,
            macos-latest,
            windows-11-arm,
            ubuntu-24.04-arm,
          ]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{ matrix.configuration }} --no-restore
      - name: Bench
        run: dotnet run -c ${{ matrix.configuration }} -f net10.0 --no-restore --project src/Sep.Benchmarks/Sep.Benchmarks.csproj -- -m -d --iterationTime 300 --filter *
