name: comparison-bench

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      filter:
        description: "BenchmarkDotNet filter"
        required: false
        default: "*"
      createPullRequest:
        description: "Create Pull Request"
        required: false
        default: false
        type: boolean

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BenchmarksDirectory: ${{ github.workspace }}/benchmarks

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        config:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-11-arm
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json
      - name: Comparison Bench
        shell: pwsh
        run: '& ./comparison-bench.ps1 -filter "${{ github.event.inputs.filter }}"'
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: benchmarks-${{ matrix.config.os }}
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.BenchmarksDirectory }}

      - name: Create Pull Request with Benchmark Results
        if: github.event.inputs.createPullRequest == 'true' && github.repository == 'nietras/Sep' && github.actor == 'nietras'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "Update ${{ env.BENCHMARK_CPU_DIRECTORY }} benchmarks for runner ${{ matrix.config.os }}"
          title: "Update ${{ env.BENCHMARK_CPU_DIRECTORY }} benchmarks for runner ${{ matrix.config.os }}"
          body: ""
          branch: "benchmarks/update-${{ env.BENCHMARK_CPU_DIRECTORY }}-${{ matrix.config.os }}"
          add-paths: |
            benchmarks/**
