name: nativeaot

permissions: read-all

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  ArtifactsDirectory: ${{ github.workspace }}/artifacts

jobs:
  nativeaot:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os: [windows-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: global.json
      - name: Publish Tester
        shell: pwsh
        run: ./publish-tester.ps1
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-${{ matrix.os }}
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.ArtifactsDirectory }}
      - name: Run Tester
        shell: pwsh
        run: ./artifacts/bin/Sep.Tester/release_net10.0_win-x64/native/Sep.Tester.exe
